jobs:
  deployAarsToNexus:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: '17'
    - continue-on-error: true
      env:
        GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
        GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
        OSSR_PASSWORD: ${{ secrets.OSSR_PASSWORD }}
        OSSR_USERNAME: ${{ secrets.OSSR_USERNAME }}
        SONATYPE_STATING_PROFILE_ID: ${{ secrets.SONATYPE_STATING_PROFILE_ID }}
      run: 'echo "${{ secrets.GPG_FILE }}" > sec.gpg.asc

        gpg -d --passphrase "${{ secrets.GPG_FILE_PSWD }}" --batch sec.gpg.asc > sec.gpg

        fastlane deployNexus

        '
      shell: bash
name: Deploy to Nexus
on:
  repository_dispatch:
    types: trigger-ga___deploy-to-nexus.yml
