jobs:
  deployInternal:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: '17'
    - continue-on-error: true
      env:
        GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
        GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
        KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
        KEYSTORE_KEY_PSWD: ${{ secrets.KEYSTORE_KEY_PSWD }}
        KEYSTORE_PSWD: ${{ secrets.KEYSTORE_PSWD }}
        OSSR_PASSWORD: ${{ secrets.OSSR_PASSWORD }}
        OSSR_USERNAME: ${{ secrets.OSSR_USERNAME }}
        SONATYPE_STATING_PROFILE_ID: ${{ secrets.SONATYPE_STATING_PROFILE_ID }}
      run: 'pwd

        echo "${{ secrets.GOOGLE_SERVICES }}" | base64 --decode > app/google-services.json

        echo "${{ secrets.KEYSTORE_FILE }}" > keystore.asc

        gpg -d --passphrase "${{ secrets.KEYSTORE_FILE_PSWD }}" --batch keystore.asc
        > keystore

        echo "${{ secrets.GPG_FILE }}" > sec.gpg.asc

        gpg -d --passphrase "${{ secrets.GPG_FILE_PSWD }}" --batch sec.gpg.asc > sec.gpg

        echo "${{ secrets.API_KEY_FILE }}" > fastlane-api.json.asc

        gpg -d --passphrase "${{ secrets.API_KEY_FILE_PSWD }}" --batch fastlane-api.json.asc
        > fastlane-api.json

        fastlane deployInternal

        '
      shell: bash
name: Deploy to Play Store Internal
on:
  repository_dispatch:
    types: trigger-ga___deploy-to-play-store.yml
